"""
Update ClientTrafficPolicy certificate fingerprints in Kubernetes.

This script:
1. Fetches an existing ClientTrafficPolicy custom resource.
2. Reads TLS certificate fingerprints from a file. The file is generated by shell script fingerprints.sh
3. Updates the policy with the new fingerprints.
4. Patches the resource back into the cluster.

Required environment variables:
- POLICY_NAME: Name of the ClientTrafficPolicy
Optional environment variables:
- POLICY_NAMESPACE: Namespace of the policy (default: default)

Usage:
    python update_fingerprint.py <fingerprints_file>
"""

import sys
import os
import logging
from kubernetes import client, config
from kubernetes.client.rest import ApiException

# -------------------------------------------------------------------
# Logging configuration
# -------------------------------------------------------------------
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] - %(message)s"
)
logger = logging.getLogger(__name__)

# -------------------------------------------------------------------
# Kubernetes client setup
# -------------------------------------------------------------------
try:
    #config.load_kube_config()
    config.load_incluster_config()
except Exception as e:
    logger.error("Failed to load kubeconfig: %s", e)
    sys.exit(1)

api = client.CustomObjectsApi()

# -------------------------------------------------------------------
# Environment variables
# -------------------------------------------------------------------
NAMESPACE = os.getenv("POLICY_NAMESPACE", "default")
POLICY_NAME = os.getenv("POLICY_NAME")

if not POLICY_NAME:
    logger.error("Environment variable POLICY_NAME must be set")
    sys.exit(1)


def get_existing_policy():
    """
    Fetch the existing ClientTrafficPolicy from the cluster.

    Returns:
        dict: ClientTrafficPolicy custom object
    """
    try:
        logger.info("Fetching ClientTrafficPolicy '%s' from namespace '%s'", POLICY_NAME, NAMESPACE)

        return api.get_namespaced_custom_object(
            group="gateway.envoyproxy.io",
            version="v1alpha1",
            namespace=NAMESPACE,
            plural="clienttrafficpolicies",
            name=POLICY_NAME
        )

    except ApiException as e:
        logger.error("Failed to fetch ClientTrafficPolicy '%s': %s", POLICY_NAME, e)
        sys.exit(2)

def fetch_fingerprints():
    """
    Read certificate fingerprints from the file passed as CLI argument.

    Returns:
        list[str]: List of fingerprint hashes
    """
    if len(sys.argv) < 2:
        logger.error("Fingerprint file path must be provided as an argument")
        sys.exit(3)

    fingerprint_file = sys.argv[1]
    logger.info("Reading fingerprints from file: %s", fingerprint_file)

    try:
        with open(fingerprint_file, "r") as fp:
            fingerprints = fp.read().strip()

        fingerprint_list = fingerprints.split()

        if not fingerprint_list:
            logger.warning("Fingerprint file '%s' is empty or contains only whitespace", fingerprint_file)

        return fingerprint_list

    except FileNotFoundError:
        logger.error("Fingerprint file not found: %s", fingerprint_file)
        sys.exit(4)
    except Exception as e:
        logger.error("Unexpected error while reading fingerprint file '%s': %s", fingerprint_file, e)
        sys.exit(5)


def update_fingerprint():
    """
    Update the ClientTrafficPolicy with new certificate fingerprints.
    """
    policy = get_existing_policy()
    fingerprints = fetch_fingerprints()

    if not fingerprints:
        logger.error("No fingerprints found. Aborting ClientTrafficPolicy update.")
        sys.exit(6)

    logger.info("Updating ClientTrafficPolicy '%s' with %d fingerprints", POLICY_NAME, len(fingerprints))

    # Update the policy spec safely
    policy["spec"]["tls"]["clientValidation"]["certificateHashes"] = fingerprints

    try:
        api.patch_namespaced_custom_object(
            group="gateway.envoyproxy.io",
            version="v1alpha1",
            namespace=NAMESPACE,
            plural="clienttrafficpolicies",
            name=POLICY_NAME,
            body=policy
        )

        logger.info("Successfully updated ClientTrafficPolicy '%s'", POLICY_NAME)

    except ApiException as e:
        logger.error("Failed to update ClientTrafficPolicy '%s': %s", POLICY_NAME, e)
        sys.exit(7)


# -------------------------------------------------------------------
# Script entry point
# -------------------------------------------------------------------
if __name__ == "__main__":
    update_fingerprint()
